<a href="https://colab.research.google.com/github/CLEV769/Arreglos_12_08_2025/blob/main/matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

#Matrices
#crear una matriz de 3x3 con valores aleatorios
matriz = np.random.randint(0, 100, (3, 3))#creamos la matriz de aleatorios , el rango es de 1 a 100 de tamaño
print(matriz)                             #3x3 esto significa que son 9 elementos
matriz2 = np.random.Generator(np.random.PCG64()).integers(0, 100, (3, 3))#creamos la matriz de aleatorios ,
print("\033[31mMatriz aleatoria 2:\033[0m ⬇")                            #el rango es de 1 a 100 de tamaño 3x3 (Esta es otra forma de hacerlo)
print(matriz2)  # Imprime la segunda matriz debajo

#crear matriz identidad de 9x9
matriz_identidad = np.eye(9) #creamos una matriz identidad de 9x9
print("\033[32mMatriz identidad:\033[0m")  # Imprime el texto
print(matriz_identidad)  # Imprime la matriz identidad

#matriz transpuesta (transpuesta = pasar de columna a fila)
matriz_transpuesta = matriz.T #transponer la matriz identidad en color verde
print("\033[33mMatriz transpuesta:\033[0m")  # Imprime el texto
print(matriz_transpuesta)  # Imprime la matriz transpuesta


matriz_zeros = np.zeros((2, 2)) #creamos una matriz de ceros de tamaño 2x2
for incrementador in range(2):
    matriz_zeros[incrementador][incrementador] = 1  # Pone 1 en la diagonal principal
print("\033[38m", matriz_zeros, "\033[0m")  # Imprime la matriz de ceros en color morado
print("-----------------------------------------------------------------")
for fila in range(2):
    for col in range(2):
        matriz_zeros[fila][col] = (np.random.randint(0,10)) + 1
print("\033[34mMatriz de ceros:\033[0m")  # Imprime el texto
print(matriz_zeros)  # Imprime la matriz de ceros

[[76 86 90]
 [78 14 29]
 [69 95 82]]
Matriz aleatoria 2: ⬇
[[64 38 48]
 [18 95  8]
 [81 53 99]]
Matriz identidad:
[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Matriz transpuesta:
[[76 78 69]
 [86 14 95]
 [90 29 82]]
 [[1. 0.]
 [0. 1.]] 
-----------------------------------------------------------------
Matriz de ceros:
[[2. 5.]
 [3. 5.]]
